#define FRAMES_MEMORIA 4
#define LIM_PROCESSOS 6
#define LIM_PAGINAS 8
#define COMECO_LRU FRAMES_MEMORIA
#define FIM_LRU (COMECO_LRU + 1)
#define TEMPO_SIMULACAO ( (LIM_PROCESSOS*3 + 20) * 1000000 )
#define WORKING_SET_LIMIT 3
