#define FRAMES_MEMORIA 64
#define LIM_PROCESSOS 20
#define LIM_PAGINAS 50
#define COMECO_LRU FRAMES_MEMORIA
#define FIM_LRU (COMECO_LRU + 1)
#define TEMPO_SIMULACAO ( (LIM_PROCESSOS*3 + 6) * 1000000 )
#define WORKING_SET_LIMIT 4



